version: '3'
services:
  tracing:
    image: "interface21/openwms-tracing:1.0.0.3"
    ports:
      - "9411:9411"


  srv:
#    build: ../../interface21/org.openwms.services
    image: "interface21/openwms-services:1.0.0.3"
    ports:
      - "8761:8761"
      
      
  cfg:
#    build: ../../interface21/org.openwms.configuration
    image: "interface21/openwms-configuration:1.0.0.2"
    hostname: cfg
    ports:
      - "8099:8099"
    environment:
      spring.cloud.config.server.git.uri: https://github.com/spring-labs/org.openwms.KARL
      spring.cloud.config.server.git.searchPaths: conf
      spring.cloud.config.server.git.clone-on-start: "true"
      owms.eureka.url: http://user:sa@srv:8761
      
      
  common-service:
#    build: ../../openwms/org.openwms.common.service
    image: "openwms/org.openwms.common.service:1.0.0.1"
    restart: on-failure:10
    hostname: common-service
    ports:
      - "8120:8120"
    environment:
      spring.cloud.config.username: user
      spring.cloud.config.password: sa
      spring.zipkin.base-url: http://tracing:9411/
      owms.eureka.url: http://user:sa@srv:8761
      
      
  tms-transportation:
#    build: ../../openwms/org.openwms.tms.transportation
    image: "openwms/org.openwms.tms.transportation:1.0.0.1"
    restart: on-failure:10
    hostname: tms-transportation
    ports:
      - "8131:8131"
    environment:
      spring.cloud.config.username: user
      spring.cloud.config.password: sa
      spring.zipkin.base-url: http://tracing:9411/
      owms.eureka.url: http://user:sa@srv:8761
      
      
  routing-service:
#    build: ../../openwms/org.openwms.tms.routing
    image: "openwms/org.openwms.tms.routing:1.0.0.1"
    restart: on-failure:10
    hostname: routing-service
    ports:
      - "8130:8130"
    environment:
      spring.cloud.config.username: user
      spring.cloud.config.password: sa
      spring.zipkin.base-url: http://tracing:9411/
      owms.eureka.url: http://user:sa@srv:8761

  tcp-palett1:
#    build: ../../openwms/org.openwms.common.comm
    image: "openwms/org.openwms.common.comm:1.0.0.1"
    restart: on-failure:10
    hostname: tcp-palett1
    ports:
      - "30001:30001"
    environment:
      spring.application.name: tcpid-palett1
      spring.cloud.config.username: user
      spring.cloud.config.password: sa
      spring.zipkin.base-url: http://tracing:9411/
      owms.eureka.url: http://user:sa@srv:8761
